services:
  web:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    stdin_open: true  # to use a debugger
    tty: true  # to use a debugger


  mysqldb:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssw0rd1
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config:
